### ISSUE TITLE
Anonymous Twitch Integration

### ISSUE THREAD

**Issue by holy-jesus** [Pinsplash/halflife2chaos#70]
I looked at the Twitch integration code, there is only chat reading and no sending messages, Twitch has an undocumented feature to connect anonymously to a chat in which you can read the chat, but not send messages. If sending messages is not planned in the integration, then it is possible to simplify the connection of the Twitch integration for the user (the user will not need to create an application on dev.twitch.tv) and simplify the code (remove authorization, refreshing tokens, etc.).

I already made a version without authorization, everything works, but I want to test it more thoroughly. If the topic is relevant, then I can create a pull request when I'm done.
You can check the code here: https://github.com/holy-jesus/halflife2chaos/tree/twitch-integration-without-auth
I tried to stick to the original version as much as possible.

Link to the forum discussion about anonymous connection to chat: https://discuss.dev.twitch.tv/t/anonymous-connection-to-twitch-chat/20392

**Comment by acuifex** [comment]
That's pretty cool, but rolling with your own implementation of twitch api isn't ideal.
There are some edge cases like [reconnect event](https://dev.twitch.tv/docs/irc/commands/#reconnect) and I'd kinda like to keep the flexibility of having all endpoints. I think it should be possible to use [TwitchApi for anonymous logins](https://github.com/Teekeks/pyTwitchAPI/blob/e5021b936e8f421f489dd3d1a9c74308e7efeb38/twitchAPI/chat/__init__.py#L1128-L1130).
Github and me kinda have issues reading your `requirements.txt`. You might want to switch your encoding to utf-8/ascii. (add a newline at the end while you're there, i forgot to do it)
I also remember obs being annoying about importing code from my own files. I'm not sure what i was doing wrong.

Also instead of creating an issue about your improvements, create the pull request in the first place. This allows for better review integrations and avoids creating kinda pointless issues.

@Pinsplash

**Comment by holy-jesus** [comment]
I tried to make an anonymous chat bot through TwitchAPI and it worked, with workarounds, but it worked. [Here is gist](https://gist.github.com/holy-jesus/9d504b476b3403542d14a8ddc425f1e6)

I slightly improved my implementation of the twitch api, added support for reconnect events, reconnecting if the connection is broken and auto-entering the channel if user changed it in the settings, the [link](https://github.com/holy-jesus/halflife2chaos/tree/twitch-integration-without-auth) is still the same.

And also I made a version without authorization using TwithApi library, here is the link: https://github.com/holy-jesus/halflife2chaos/tree/twitchapi-without-auth

As for importing files into OBS, I did not encounter any problems, maybe this is a bug in some older version of OBS, I have the latest one installed `29.1.3`.

Sorry about the useless issue, this is my first time contributing to any project, so this is all new to me. For which version should I create a pull request, with my implementation of the twitch api or with the TwithApi library?

**Comment by holy-jesus** [comment]
I added comments, should I create a pull request?

**Comment by acuifex** [comment]
> should I create a pull request?

I think so, yeah

> I added comments

Just saying that it's mocking `Twitch` to allow anonymous logins would've sufficed, but some verbosity doesn't hurt

**Comment by Pinsplash** [comment]
while we're here, couldn't we replace the cmd part with a batch file?

**Comment by holy-jesus** [comment]
Yes, that's a good idea, I'll do it

**Comment by holy-jesus** [comment]
Created a bat file, I tried to automate as much as possible. Also updated README.md

**Comment by Pinsplash** [comment]
worked flawlessly, very nice
